# Generated by Django 4.2.5 on 2023-10-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cut',
            old_name='tencut',
            new_name='ten',
        ),
    ]
